services:
  localstack:
    container_name: pokemon-localstack
    image: localstack/localstack
    ports:
      - "4566:4566" # LocalStack Gateway
    environment:
      - SERVICES=s3, dynamodb
      - DEBUG=1
    volumes:
      - localstack-data:/var/lib/localstack
      - /var/run/docker.sock:/var/run/docker.sock
  pokemon-api:
    container_name: pokemon-api
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - "5001:5000"
    environment:
      - ENDPOINT_URL=http://localstack:4566
    depends_on:
      - localstack
volumes:
  localstack-data: