name: CI/CD Pipeline Part 3 (Pokemon Tests)

on:
  push:
    branches: [ main ] # just a hw assignment, so there are no branches
  pull_request:
    branches: [ main ]
  workflow_dispatch: # to manually trigger :D

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Install Docker Compose
      run: |
        sudo curl -L "https://github.com/docker/compose/releases/download/v2.27.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
        sudo chmod +x /usr/local/bin/docker-compose
        docker-compose version

    - name: Make scripts executable
      run: chmod +x scripts/run_tests.sh 

    - name: Run the tests in Docker
      run: ./scripts/run_tests.sh

